server:
  port: 8082
Spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 39.96.177.174:8848
#        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
         服务的ID，唯一即可一般与微服务的service name一致
        - id: main_module
          # lb表示负载均衡
          uri: lb://test-server
          predicates:
            # 路径匹配,所有user开头的请求都转发到localhost:8080
            - Path=/home/**

        - id: analysis
          uri: https://mawrgorshin.com
          predicates:
            - Path=/ocean/**
          filters:
            - StripPrefix=1
#        - id: nacos-provid
#          uri: lb://test-server
#          predicates:
#            - Path=/server/**
#          filters:
#            - StripPrefix=1
